feat: add checkbox column helper
FlowingCode/GridHelpers pull request #89
Opened 2023-08-11 14:33 UTC by flang

Given that Vaadin's Grid doesn't provide a way to know when its dataprovider changes, if Select All checkbox is visible, and in order to keep it in sync with grid data, user must explicitly refresh the CheckboxColumn invoking refresh() method.

Close #69

2023-08-11 16:11 UTC, javier-godoy requested changes

2023-08-11 16:11 UTC, javier-godoy commented on src/test/java/com/flowingcode/vaadin/addons/gridhelpers/AllFeaturesDemo.java
> +        .setHidingToggleCaption("Last name column");
Formatting changes in lines that are not modified

2023-08-11 16:11 UTC, javier-godoy commented on src/test/java/com/flowingcode/vaadin/addons/gridhelpers/AllFeaturesDemo.java
> +    grid.setItems(TestData.initializeData());
Line moved, apparently unrelated to the implemented feature.

2023-08-11 16:11 UTC, javier-godoy commented on src/test/java/com/flowingcode/vaadin/addons/gridhelpers/AllFeaturesDemo.java
> +
Formatting change

2023-08-11 16:11 UTC, javier-godoy commented on src/main/resources/META-INF/frontend/fcGridHelper/vaadin-checkbox.css
> +:host([theme~='checkbox-top']) .vaadin-checkbox-container [part="checkbox"] {
Use some prefix such as `fcgh-checkbox-top` in order to avoid collision with application-defined themes.

2023-08-11 16:11 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/gridhelpers/CheckboxColumnGridHelper.java
> + * This file incorporates work licensed under the Apache License, Version 2.0 from Vaadin Cookbook
Does it?

2023-08-11 16:11 UTC, javier-godoy commented on src/main/java/com/flowingcode/vaadin/addons/gridhelpers/CheckboxColumnGridHelper.java
> + * This file incorporates work licensed under the Apache License, Version 2.0 from Vaadin Cookbook
Which recipe is this code based on?

2023-08-11 16:36 UTC, flang commented on src/main/java/com/flowingcode/vaadin/addons/gridhelpers/CheckboxColumnGridHelper.java
> + * This file incorporates work licensed under the Apache License, Version 2.0 from Vaadin Cookbook
definitely not, gonna remove it

2023-08-11 16:50 UTC, flang commented on src/test/java/com/flowingcode/vaadin/addons/gridhelpers/AllFeaturesDemo.java
> +    grid.setItems(TestData.initializeData());
fixed

2023-08-11 16:50 UTC, flang commented on src/test/java/com/flowingcode/vaadin/addons/gridhelpers/AllFeaturesDemo.java
> +        .setHidingToggleCaption("Last name column");
fixed

2023-08-11 16:50 UTC, flang commented on src/test/java/com/flowingcode/vaadin/addons/gridhelpers/AllFeaturesDemo.java
> +
fixed

2023-08-11 16:50 UTC, flang commented on src/main/resources/META-INF/frontend/fcGridHelper/vaadin-checkbox.css
> +:host([theme~='checkbox-top']) .vaadin-checkbox-container [part="checkbox"] {
fixed

2023-08-11 16:50 UTC, flang commented on src/main/java/com/flowingcode/vaadin/addons/gridhelpers/CheckboxColumnGridHelper.java
> + * This file incorporates work licensed under the Apache License, Version 2.0 from Vaadin Cookbook
fixed

2023-10-24 17:35 UTC, javier-godoy approved these changes

2023-10-24 17:36 UTC, merged